development:
  adapter: postgresql
  encoding: unicode
  database: fbo_development
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  encoding: unicode
  database: fbo_test
  pool: 5
  timeout: 5000


